### ISSUE TITLE
Can't cross-compile GCC for FreeBSD

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/julia-docker#13]
@ararslan @wdv4758h

I've been trying to cross-compile a `gcc` and friends for FreeBSD so that we can get `gfortran` as well.  I'm running into the following problem:

```
/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/bin/ld: /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/
lib/libpthread.a(thr_spec.o): relocation R_X86_64_32 against hidden symbol `_keytable_lock' can not be used when making a shared object
/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/bin/ld: /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/
lib/libpthread.a(thr_sig.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/bin/ld: /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/
lib/libpthread.a(thr_once.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fP
IC
/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/bin/ld: /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/
lib/libpthread.a(thr_mutex.o): relocation R_X86_64_32 against hidden symbol `_pthread_mutexattr_default' can not be used when making a
shared object
....
```

It looks to me like the libraries that are coming from the FreeBSD base image were not compiled with `-fPIC`, which means that they can't be linked into shared libraries.  This seems like a big problem.  Do you guys have any ideas on what to do about this?  Does FreeBSD just never make shared libraries?

**Comment by ararslan** [comment]
> Does FreeBSD just never make shared libraries?

No, it definitely does.

Check out FreeBSD's official GCC port to see if there's anything in particular they're doing for setup that would be relevant here: https://svnweb.freebsd.org/ports/head/base/gcc/files/.

**Comment by ararslan** [comment]
@wdv4758h or @iblis17, any ideas?

**Comment by iblislin** [comment]
How about just fetching the prebuilt GCC binary from official pkg's repo?

**Comment by staticfloat** [comment]
This is a cross-compiler, not a native BSD compiler.

**Comment by wdv4758h** [comment]
Um, the annoy part of GCC, it needs specific build to support cross compilation.
LLVM tools just work out of the box.

**Comment by wdv4758h** [comment]
FreeBSD pthread implementation is called libthr, you should see symbolic links like this:
```
usr/lib/libpthread.a -> usr/lib/libthr.a
usr/lib/libpthread.so -> usr/lib/libthr.so -> lib/libthr.so.3
```

Maybe it should be fine if it we somehow make it choose the libpthread.so ?

----

Just FYI, this might help: https://linux-tips.com/t/how-to-build-a-freebsd-toolchain-for-linux/288
I didn't test it, but the steps look good.

**Comment by ararslan** [comment]
A guru has informed me that FreeBSD libraries are not compiled with -fPIC because there's no ASLR in FreeBSD. He said that as an alternative, we may be able to use a [HardenedBSD](https://hardenedbsd.org/) base, a FreeBSD derivative, as that does have ASLR and consequently compiles its libraries with -fPIC. But he's unsure of how that would affect compatibility with regular FreeBSD.
