### ISSUE TITLE
distroless Docker image for Julia

### ISSUE THREAD

**Issue by s-celles** [staticfloat/julia-docker#16]
Hello,

Google did https://github.com/GoogleContainerTools/distroless
I wonder if there is some benefits for Julia to have such a language focused docker image (minus the operating system).

Kind regard

PS : I should probably have asked this at https://discourse.julialang.org/ but it's currently unavailable

**Comment by staticfloat** [comment]
This isn't something I think we really have a need for at this point, but if you're interested in it, I encourage you to make a pull request to the https://github.com/GoogleContainerTools/distroless repository!
